<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Seed hardcoded order data for the order module.
     */
    public function run(): void
    {
        $now = now();

        // Step 1: seed fixed order header rows.
        DB::table('orders')->upsert([
            [
                'id' => 1,
                'placed_by_user_id' => 1,
                'company_id' => null,
                'status' => 'draft',
                'currency' => 'INR',
                'subtotal_amount' => 2400.0000,
                'tax_amount' => 120.0000,
                'discount_amount' => 0.0000,
                'shipping_amount' => 0.0000,
                'adjustment_amount' => 0.0000,
                'rounding_amount' => 0.0000,
                'total_amount' => 2520.0000,
                'pricing_snapshot' => '{"currency":"INR","items_count":1,"price_source":"current_visible_price","subtotal_amount":2400,"tax_amount":120,"discount_amount":0,"items_total":2520,"shipping_amount":0,"adjustment_amount":0,"rounding_amount":0,"total_amount":2520,"price_types":["public"]}',
                'notes' => 'Draft order seeded for gloves.',
                'submitted_at' => null,
                'approved_at' => null,
                'cancelled_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'placed_by_user_id' => 1,
                'company_id' => 1,
                'status' => 'submitted',
                'currency' => 'INR',
                'subtotal_amount' => 242400.0000,
                'tax_amount' => 43488.0000,
                'discount_amount' => 0.0000,
                'shipping_amount' => 1500.0000,
                'adjustment_amount' => 0.0000,
                'rounding_amount' => 0.0000,
                'total_amount' => 287388.0000,
                'pricing_snapshot' => '{"currency":"INR","items_count":2,"price_source":"current_visible_price","subtotal_amount":242400,"tax_amount":43488,"discount_amount":0,"items_total":285888,"shipping_amount":1500,"adjustment_amount":0,"rounding_amount":0,"total_amount":287388,"price_types":["public"]}',
                'notes' => 'Submitted seeded order with two items.',
                'submitted_at' => $now,
                'approved_at' => null,
                'cancelled_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'placed_by_user_id' => 1,
                'company_id' => 1,
                'status' => 'cancelled',
                'currency' => 'INR',
                'subtotal_amount' => 265000.0000,
                'tax_amount' => 47700.0000,
                'discount_amount' => 0.0000,
                'shipping_amount' => 0.0000,
                'adjustment_amount' => 0.0000,
                'rounding_amount' => 0.0000,
                'total_amount' => 312700.0000,
                'pricing_snapshot' => '{"currency":"INR","items_count":1,"price_source":"current_visible_price","subtotal_amount":265000,"tax_amount":47700,"discount_amount":0,"items_total":312700,"shipping_amount":0,"adjustment_amount":0,"rounding_amount":0,"total_amount":312700,"price_types":["retail"]}',
                'notes' => 'Cancelled seeded order for testing status changes.',
                'submitted_at' => null,
                'approved_at' => null,
                'cancelled_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ], ['id'], [
            'placed_by_user_id',
            'company_id',
            'status',
            'currency',
            'subtotal_amount',
            'tax_amount',
            'discount_amount',
            'shipping_amount',
            'adjustment_amount',
            'rounding_amount',
            'total_amount',
            'pricing_snapshot',
            'notes',
            'submitted_at',
            'approved_at',
            'cancelled_at',
            'updated_at',
            'deleted_at',
        ]);

        // Step 2: seed fixed order item rows under the seeded orders.
        DB::table('order_items')->upsert([
            [
                'id' => 1,
                'order_id' => 1,
                'product_id' => 6,
                'product_variant_id' => 7,
                'sku' => 'BIO-GLV-001-100',
                'product_name' => 'Nitrile Gloves',
                'variant_name' => 'Pack 100',
                'description' => 'Resolved from current visible product price.',
                'quantity' => 20,
                'unit_price' => 120.0000,
                'subtotal_amount' => 2400.0000,
                'discount_amount' => 0.0000,
                'tax_amount' => 120.0000,
                'total_amount' => 2520.0000,
                'sort_order' => 0,
                'item_snapshot' => '{"currency":"INR","price_type":"public","gst_rate":5,"unit_tax_amount":6,"unit_price_after_gst":126,"min_order_quantity":10,"max_order_quantity":500,"lot_size":10,"product_variant_id":7,"variant_sku":"BIO-GLV-001-100","variant_name":"Pack 100"}',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'order_id' => 2,
                'product_id' => 5,
                'product_variant_id' => 6,
                'sku' => 'BIO-ECG-3000-BASE',
                'product_name' => 'ECG Machine CardioMax 3000',
                'variant_name' => 'Base',
                'description' => 'Resolved from current visible product price.',
                'quantity' => 2,
                'unit_price' => 120000.0000,
                'subtotal_amount' => 240000.0000,
                'discount_amount' => 0.0000,
                'tax_amount' => 43200.0000,
                'total_amount' => 283200.0000,
                'sort_order' => 0,
                'item_snapshot' => '{"currency":"INR","price_type":"public","gst_rate":18,"unit_tax_amount":21600,"unit_price_after_gst":141600,"min_order_quantity":1,"max_order_quantity":25,"lot_size":1,"product_variant_id":6,"variant_sku":"BIO-ECG-3000-BASE","variant_name":"Base"}',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'order_id' => 2,
                'product_id' => 7,
                'product_variant_id' => 8,
                'sku' => 'BIO-SYR-050-50',
                'product_name' => 'Sterile Syringe Pack',
                'variant_name' => 'Pack 50',
                'description' => 'Resolved from current visible product price.',
                'quantity' => 30,
                'unit_price' => 80.0000,
                'subtotal_amount' => 2400.0000,
                'discount_amount' => 0.0000,
                'tax_amount' => 288.0000,
                'total_amount' => 2688.0000,
                'sort_order' => 1,
                'item_snapshot' => '{"currency":"INR","price_type":"public","gst_rate":12,"unit_tax_amount":9.6,"unit_price_after_gst":89.6,"min_order_quantity":10,"max_order_quantity":500,"lot_size":10,"product_variant_id":8,"variant_sku":"BIO-SYR-050-50","variant_name":"Pack 50"}',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'order_id' => 3,
                'product_id' => 1,
                'product_variant_id' => 1,
                'sku' => 'BIO-HEMA-X200-STD',
                'product_name' => 'Hematology Analyzer X200',
                'variant_name' => 'Standard',
                'description' => 'Resolved from current visible product price.',
                'quantity' => 1,
                'unit_price' => 265000.0000,
                'subtotal_amount' => 265000.0000,
                'discount_amount' => 0.0000,
                'tax_amount' => 47700.0000,
                'total_amount' => 312700.0000,
                'sort_order' => 0,
                'item_snapshot' => '{"currency":"INR","price_type":"retail","gst_rate":18,"unit_tax_amount":47700,"unit_price_after_gst":312700,"min_order_quantity":1,"max_order_quantity":20,"lot_size":1,"product_variant_id":1,"variant_sku":"BIO-HEMA-X200-STD","variant_name":"Standard"}',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id'], [
            'order_id',
            'product_id',
            'product_variant_id',
            'sku',
            'product_name',
            'variant_name',
            'description',
            'quantity',
            'unit_price',
            'subtotal_amount',
            'discount_amount',
            'tax_amount',
            'total_amount',
            'sort_order',
            'item_snapshot',
            'updated_at',
        ]);
    }
}
