<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RbacSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('permission_role')->delete();
        DB::table('user_permissions')->delete();
        DB::table('permissions')->delete();
        DB::table('roles')->delete();

        DB::table('roles')->insert([
            ['id' => 1, 'name' => 'Guest', 'slug' => 'guest', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'B2C Customer', 'slug' => 'b2c_customer', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'B2B User', 'slug' => 'b2b_user', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Internal User', 'slug' => 'internal_user', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Internal User - Sales', 'slug' => 'internal_user_sales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Internal User - Finance', 'slug' => 'internal_user_finance', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Internal User - Support', 'slug' => 'internal_user_support', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Internal User - Logistics', 'slug' => 'internal_user_logistics', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'Admin', 'slug' => 'admin', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'Delegated Admin', 'slug' => 'delegated_admin', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('permissions')->insert([
            ['id' => 1, 'name' => 'home', 'slug' => 'home', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'home.page', 'slug' => 'home.page', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'products.index', 'slug' => 'products.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'products.productDetails', 'slug' => 'products.productDetails', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'products.technical-resources.download', 'slug' => 'products.technical-resources.download', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'cart.data', 'slug' => 'cart.data', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'cart.items.store', 'slug' => 'cart.items.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'cart.items.update', 'slug' => 'cart.items.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'cart.items.destroy', 'slug' => 'cart.items.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'cart.checkout.submit', 'slug' => 'cart.checkout.submit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'name' => 'guest-cart.data', 'slug' => 'guest-cart.data', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'name' => 'guest-cart.items.store', 'slug' => 'guest-cart.items.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'name' => 'guest-cart.items.update', 'slug' => 'guest-cart.items.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'name' => 'guest-cart.items.destroy', 'slug' => 'guest-cart.items.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'name' => 'checkout.page', 'slug' => 'checkout.page', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'name' => 'checkout.submit', 'slug' => 'checkout.submit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'name' => 'checkout.coupon.validate', 'slug' => 'checkout.coupon.validate', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'name' => 'checkout.reorder.pricing', 'slug' => 'checkout.reorder.pricing', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'name' => 'checkout.buy-now', 'slug' => 'checkout.buy-now', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'name' => 'guest.checkout.buy-now', 'slug' => 'guest.checkout.buy-now', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'name' => 'orders.index', 'slug' => 'orders.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'name' => 'orders.store', 'slug' => 'orders.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'name' => 'orders.reorder.checkout', 'slug' => 'orders.reorder.checkout', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'name' => 'orders.reorder.checkout.submit', 'slug' => 'orders.reorder.checkout.submit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'name' => 'orders.reorder', 'slug' => 'orders.reorder', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'name' => 'orders.show', 'slug' => 'orders.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'name' => 'orders.update', 'slug' => 'orders.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'name' => 'orders.destroy', 'slug' => 'orders.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'name' => 'pi-quotation.generate', 'slug' => 'pi-quotation.generate', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'name' => 'pi-quotation.store', 'slug' => 'pi-quotation.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'name' => 'quotation.create', 'slug' => 'quotation.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'name' => 'quotation.store', 'slug' => 'quotation.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'name' => 'diagnostic-quiz', 'slug' => 'diagnostic-quiz', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'name' => 'diagnostic-quiz.store', 'slug' => 'diagnostic-quiz.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'name' => 'book-meeting', 'slug' => 'book-meeting', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'name' => 'book-meeting.store', 'slug' => 'book-meeting.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'name' => 'about', 'slug' => 'about', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'name' => 'contact', 'slug' => 'contact', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'name' => 'contact.store', 'slug' => 'contact.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'name' => 'privacy', 'slug' => 'privacy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'name' => 'terms', 'slug' => 'terms', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'name' => 'refund-policy', 'slug' => 'refund-policy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'name' => 'faq', 'slug' => 'faq', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'name' => 'maintenance', 'slug' => 'maintenance', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'name' => 'customer.profile.preview', 'slug' => 'customer.profile.preview', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'name' => 'customer.profile.update', 'slug' => 'customer.profile.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'name' => 'customer.profile.password.update', 'slug' => 'customer.profile.password.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'name' => 'customer.addresses.preview', 'slug' => 'customer.addresses.preview', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'name' => 'customer.orders.preview', 'slug' => 'customer.orders.preview', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'name' => 'customer.addresses.store', 'slug' => 'customer.addresses.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'name' => 'customer.addresses.update', 'slug' => 'customer.addresses.update', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'name' => 'support-tickets.index', 'slug' => 'support-tickets.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'name' => 'support-tickets.store', 'slug' => 'support-tickets.store', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'name' => 'support-tickets.attachments.download', 'slug' => 'support-tickets.attachments.download', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'name' => 'support-tickets.show', 'slug' => 'support-tickets.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'name' => 'order.confirmation', 'slug' => 'order.confirmation', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('permission_role')->insert([
            ['role_id' => 1, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 1, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 2, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 3, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 4, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 5, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 6, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 7, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 8, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 9, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['role_id' => 10, 'permission_id' => 56, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
