<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $proforma->pi_number }}</title>

    <style>
        @page {
            size: {{ strtoupper(config('invoice.pdf.paper', 'a4')) }};
            margin: {{ config('invoice.pdf.margin_top', '10mm') }} {{ config('invoice.pdf.margin_right', '10mm') }} {{ config('invoice.pdf.margin_bottom', '12mm') }} {{ config('invoice.pdf.margin_left', '10mm') }};
        }

        * { box-sizing: border-box; }

        body {
            margin: 0;
            font-family: "Times New Roman", Times, serif;
            font-size: 12px;
            color: #000;
        }

        .sheet {
            padding: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid #000;
            padding: 4px 6px;
            vertical-align: top;
        }

        .center { text-align: center; }
        .right { text-align: right; }
        .bold { font-weight: 700; }
        .italic { font-style: italic; }
        .small { font-size: 11px; }
        .nowrap { white-space: nowrap; }
        .no-pad { padding: 0 !important; }

        .header-title {
            font-size: 18px;
            font-weight: 700;
            letter-spacing: 0.5px;
        }

        .header-subtitle {
            font-size: 16px;
            font-weight: 700;
        }

        .logo-box {
            width: 22%;
            text-align: center;
            vertical-align: middle;
        }

        .logo-box img {
            max-width: 150px;
            height: auto;
            display: inline-block;
        }

        .addr-lines { line-height: 1.25; }

        .grid-label {
            width: 8%;
            font-weight: 700;
            white-space: nowrap;
        }

        .grid-left {
            width: 32%;
        }

        .grid-mid {
            width: 35%;
        }

        .grid-rlabel {
            width: 10%;
            font-weight: 700;
            white-space: nowrap;
        }

        .grid-rval {
            width: 15%;
            white-space: nowrap;
            font-weight: 700;
        }

        .items thead th {
            background: #d9d9d9;
            font-weight: 700;
            text-align: center;
        }

        .items td { height: 22px; }

        .hl-yellow { background: #fff26a; font-weight: 700; }
        .hl-green { background: #8fd16b; font-weight: 700; }
        .text-red { color: #c00000; font-weight: 700; }

        .total-row td { font-weight: 700; }
        .grand-total {
            background: #e60000;
            color: #fff;
            font-weight: 700;
        }

        .bank {
            margin-top: 14px;
            color: #c00000;
            font-weight: 700;
        }

        .bank .line {
            margin-top: 6px;
            font-weight: 700;
        }

        .sig-logo {
            max-width: 120px;
            height: auto;
            display: inline-block;
            margin: 6px 0;
        }
    </style>
</head>
<body>
@php
    // Step 1: load static invoice settings from config.
    $currency = $proforma->currency ?: config('invoice.pdf.currency', 'INR');
    $sellerName = config('invoice.company.name');
    $sellerGstin = config('invoice.company.gstin');
    $sellerStateCode = config('invoice.company.state_code');
    $sellerAddressLines = config('invoice.company.address_lines', []);
    $documentTitle = config('invoice.branding.document_title', 'PROFORMA INVOICE');
    $amountInWordsLabel = config('invoice.branding.amount_in_words_label', 'Amount in Rupees:');
    $autoGeneratedText = config('invoice.branding.auto_generated_text', 'Auto-Generated Proforma,');
    $signatureNote = config('invoice.branding.signature_note', 'Signature not required.');
    $bankHeading = config('invoice.branding.bank_heading', 'Bank Details:');
    $termsHeading = config('invoice.terms.heading', 'TERMS : E.&O.E.');
    $termsItems = config('invoice.terms.items', []);
    $bankLines = config('invoice.bank.lines', []);

    // Step 2: convert the configured logo into a data URI for DomPDF.
    $logoAbsolutePath = public_path(config('invoice.company.logo_path', 'images/biogenix-logo.png'));
    $logoDataUri = null;

    if (is_file($logoAbsolutePath)) {
        $ext = strtolower(pathinfo($logoAbsolutePath, PATHINFO_EXTENSION)) ?: 'png';
        $logoDataUri = 'data:image/'.$ext.';base64,'.base64_encode(file_get_contents($logoAbsolutePath));
    }

    // Step 3: build formatted invoice dates.
    $dt = $proforma->created_at ?? now();
    $dateDisplay = $dt->format(config('invoice.pdf.date_display_format', 'dS M-Y'));
    $datedDisplay = $dt->format(config('invoice.pdf.dated_display_format', 'd-m-Y'));

    // Step 4: prepare billing and shipping blocks from invoice data.
    $billingName = $proforma->targetCompany?->name ?: ($proforma->target_name ?: 'Customer');
    $billingGstin = $proforma->target_gstin ?? null;

    $billingLines = array_filter([
        $proforma->target_name ?: null,
        $proforma->target_address_line1 ?? null,
        $proforma->target_address_line2 ?? null,
        $proforma->target_city ?? null,
        $proforma->target_state ?? null,
        $proforma->target_pincode ?? null,
    ]);

    $shippingName = $proforma->shipping_name ?? $billingName;
    $shippingGstin = $proforma->shipping_gstin ?? $billingGstin;

    $shippingLines = array_filter([
        $proforma->shipping_address_line1 ?? null,
        $proforma->shipping_address_line2 ?? null,
        $proforma->shipping_city ?? null,
        $proforma->shipping_state ?? null,
        $proforma->shipping_pincode ?? null,
    ]);

    $enquiryNo = $proforma->enquiry_no ?? 'Telephonic';
    $kindAttn = $proforma->kind_attn ?? null;
    $attnContact = $proforma->attn_contact ?? null;

    // Step 5: read optional extra-charge values from the invoice data.
    $freight = (float) ($proforma->freight_amount ?? 0);
    $freightTax = (float) ($proforma->freight_tax_amount ?? 0);
    $roundOff = (float) ($proforma->round_off_amount ?? 0);

    // Step 6: calculate totals shown in the footer area.
    $qtyTotal = (float) $proforma->items->sum('quantity');
    $gstTotal = (float) ($proforma->tax_amount ?? 0);
    $baseTotal = (float) ($proforma->total_amount ?? 0);
    $grandTotal = (float) ($proforma->grand_total_amount ?? ($baseTotal + $freight + $freightTax + $roundOff));

    // Step 7: convert the final amount to words when ext-intl is available.
    $amountWords = null;
    try {
        if (class_exists(\NumberFormatter::class)) {
            $fmt = new \NumberFormatter('en_IN', \NumberFormatter::SPELLOUT);
            $amountWords = ucwords(trim($fmt->format($grandTotal))) . ' Rupees Only';
        }
    } catch (\Throwable $e) {
        $amountWords = null;
    }

    // Step 8: pad the item grid with blank rows for a consistent print layout.
    $minRows = (int) config('invoice.pdf.minimum_item_rows', 16);
    $blankRows = max(0, $minRows - (int) $proforma->items->count());
@endphp

<div class="sheet">
    <table>
        <tr>
            <td class="logo-box" rowspan="2">
                @if($logoDataUri)
                    <img src="{{ $logoDataUri }}" alt="Logo">
                @else
                    <div class="bold center">LOGO</div>
                @endif
            </td>
            <td class="center header-title">{{ $documentTitle }}</td>
        </tr>
        <tr>
            <td class="center header-subtitle">{{ $sellerName }}</td>
        </tr>
        <tr>
            <td colspan="2" class="center small addr-lines">
                @foreach($sellerAddressLines as $line)
                    {{ $line }}<br>
                @endforeach
            </td>
        </tr>
    </table>

    <table>
        <colgroup>
            <col class="grid-label">
            <col class="grid-left">
            <col class="grid-mid">
            <col class="grid-rlabel">
            <col class="grid-rval">
        </colgroup>

        <tr>
            <td class="bold">GSTIN</td>
            <td class="bold">{{ $sellerGstin }}</td>
            <td class="bold">Shipping Address</td>
            <td class="bold">STATE CODE:</td>
            <td class="bold">{{ $sellerStateCode }}</td>
        </tr>

        <tr>
            <td class="bold">No.</td>
            <td class="bold">{{ $proforma->pi_number }}</td>

            <td rowspan="2">
                <div class="bold">{{ $shippingName }}</div>

                @if(count($shippingLines))
                    <div>{{ implode(', ', $shippingLines) }}</div>
                @endif

                <div class="bold" style="margin-top: 2px;">
                    GST.: {{ $shippingGstin ?: '-' }}
                </div>
            </td>

            <td class="bold">Date:</td>
            <td class="bold">{{ $dateDisplay }}</td>
        </tr>

        <tr>
            <td class="bold">M/s</td>
            <td>
                <div class="bold">{{ $billingName }}</div>

                @if(count($billingLines))
                    <div>{{ implode(', ', $billingLines) }}</div>
                @endif

                <div class="bold" style="margin-top: 2px;">
                    GST.: {{ $billingGstin ?: '-' }}
                </div>
            </td>

            <td colspan="2">
                <div class="bold">
                    Kind Attn: {{ $kindAttn ?: '-' }}
                </div>
                <div class="bold" style="margin-top: 2px;">
                    Attn Contact: {{ $attnContact ?: '-' }}
                </div>
            </td>
        </tr>

        <tr>
            <td colspan="2" class="bold">
                Your Enquiry No.: <span style="font-weight:400;">{{ $enquiryNo }}</span>
            </td>
            <td class="bold">&nbsp;</td>
            <td colspan="2" class="bold">Dated: <span style="font-weight:400;">{{ $datedDisplay }}</span></td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th style="width:6%;">S. No.</th>
                <th style="width:14%;">Cat. No.</th>
                <th style="width:26%;">Product</th>
                <th style="width:14%;">Pack Size</th>
                <th style="width:8%;">Qty</th>
                <th style="width:10%;">Rate</th>
                <th style="width:10%;">Value</th>
                <th style="width:6%;">GST</th>
                <th style="width:16%;">Total Price (Inc. Vat)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($proforma->items as $item)
                @php
                    $qty = (float) ($item->quantity ?? 0);
                    $value = (float) ($item->line_subtotal ?? 0);
                    $gst = (float) ($item->line_tax_amount ?? 0);
                    $disc = (float) ($item->line_discount_amount ?? 0);
                    $rate = $qty > 0 ? ($value / $qty) : 0;
                    $totalInc = (float) ($item->line_total ?? ($value + $gst - $disc));
                    $pack = $item->pack_size ?? ($item->variant_name ?? '');
                    $catNo = $item->cat_no ?? ($item->sku ?? '');
                @endphp

                <tr>
                    <td class="center">{{ $loop->iteration }}</td>
                    <td class="center">{{ $catNo }}</td>
                    <td class="hl-yellow">{{ $item->product_name }}</td>
                    <td class="hl-green center">{{ $pack }}</td>
                    <td class="right">{{ number_format($qty, 2, '.', '') }}</td>
                    <td class="right text-red">{{ number_format($rate, 2, '.', '') }}</td>
                    <td class="right">{{ number_format($value, 2, '.', '') }}</td>
                    <td class="right">{{ number_format($gst, 2, '.', '') }}</td>
                    <td class="right">{{ number_format($totalInc, 2, '.', '') }}</td>
                </tr>
            @endforeach

            @for($i = 0; $i < $blankRows; $i++)
                <tr>
                    <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                    <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                </tr>
            @endfor

            @if($freight != 0 || $freightTax != 0 || $roundOff != 0)
                <tr>
                    <td colspan="7">&nbsp;</td>
                    <td class="right bold">FREIGHT</td>
                    <td class="right">{{ number_format($freight, 2, '.', '') }}</td>
                </tr>
                <tr>
                    <td colspan="7">&nbsp;</td>
                    <td class="right bold">FREIGHT TAX(18%)</td>
                    <td class="right">{{ number_format($freightTax, 2, '.', '') }}</td>
                </tr>
                <tr>
                    <td colspan="7">&nbsp;</td>
                    <td class="right bold">ROUND OFF</td>
                    <td class="right">{{ $roundOff >= 0 ? '+' : '' }}{{ number_format($roundOff, 2, '.', '') }}</td>
                </tr>
            @endif

            <tr class="total-row">
                <td colspan="4" class="center bold">TOTAL</td>
                <td class="right bold">{{ number_format($qtyTotal, 2, '.', '') }}</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td class="right bold">{{ number_format($gstTotal, 2, '.', '') }}</td>
                <td class="right grand-total">{{ number_format($grandTotal, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <table>
        <tr>
            <td style="width:20%;" class="bold">{{ $amountInWordsLabel }}</td>
            <td class="bold">{{ $amountWords ?: '-' }}</td>
        </tr>
    </table>

    <table>
        <tr>
            <td style="width:70%;" class="no-pad">
                <table>
                    <tr>
                        <td colspan="2" class="bold">{{ $termsHeading }}</td>
                    </tr>
                    @foreach($termsItems as $termIndex => $termText)
                        <tr>
                            <td style="width:8%;" class="center">{{ $termIndex + 1 }}</td>
                            <td>{{ $termText }}</td>
                        </tr>
                    @endforeach
                </table>
            </td>
            <td style="width:30%;" class="center">
                <div class="italic bold">{{ $autoGeneratedText }}</div>

                @if($logoDataUri)
                    <img class="sig-logo" src="{{ $logoDataUri }}" alt="Logo">
                @endif

                <div class="italic bold">{{ $signatureNote }}</div>
            </td>
        </tr>
    </table>

    <div class="bank">
        <div>{{ $bankHeading }}</div>
        @foreach($bankLines as $bankLine)
            <div class="line">{{ $bankLine }}</div>
        @endforeach
    </div>
</div>
</body>
</html>
