<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $proforma->pi_number }}</title>
    <style>
        @page {
            size: {{ strtoupper(config('invoice.pdf.paper', 'a4')) }};
            margin: {{ config('invoice.pdf.margin_top', '10mm') }} {{ config('invoice.pdf.margin_right', '10mm') }} {{ config('invoice.pdf.margin_bottom', '12mm') }} {{ config('invoice.pdf.margin_left', '10mm') }};
        }

        * { box-sizing: border-box; }
        body {
            margin: 0;
            color: #111827;
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            line-height: 1.45;
        }

        .title {
            font-size: 22px;
            font-weight: 700;
            margin: 0 0 4px;
        }

        .muted {
            color: #4b5563;
        }

        .section {
            margin-top: 18px;
        }

        .box {
            border: 1px solid #d1d5db;
            padding: 12px;
        }

        .header-table,
        .info-table,
        .items-table,
        .totals-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td,
        .info-table td,
        .items-table th,
        .items-table td,
        .totals-table td {
            border: 1px solid #d1d5db;
            padding: 8px;
            vertical-align: top;
        }

        .header-table td,
        .info-table td,
        .totals-table td {
            border-color: #e5e7eb;
        }

        .items-table th {
            background: #f3f4f6;
            font-weight: 700;
            text-align: left;
        }

        .right { text-align: right; }
        .center { text-align: center; }
        .bold { font-weight: 700; }
        .logo {
            max-width: 120px;
            height: auto;
        }
        .label {
            display: inline-block;
            min-width: 90px;
            font-weight: 700;
        }
        .totals-wrap {
            width: 42%;
            margin-left: auto;
            margin-top: 12px;
        }
        .grand-total td {
            background: #111827;
            color: #fff;
            font-weight: 700;
        }
        .small-line {
            margin: 0 0 4px;
        }
    </style>
</head>
<body>
@php
    $currency = $proforma->currency ?: config('invoice.pdf.currency', 'INR');
    $sellerName = config('invoice.company.name');
    $sellerGstin = config('invoice.company.gstin');
    $sellerStateCode = config('invoice.company.state_code');
    $sellerAddressLines = config('invoice.company.address_lines', []);
    $documentTitle = config('invoice.branding.document_title', 'PROFORMA INVOICE');
    $amountInWordsLabel = config('invoice.branding.amount_in_words_label', 'Amount in Rupees:');
    $autoGeneratedText = config('invoice.branding.auto_generated_text', 'Auto-Generated Proforma,');
    $signatureNote = config('invoice.branding.signature_note', 'Signature not required.');
    $bankHeading = config('invoice.branding.bank_heading', 'Bank Details:');
    $termsHeading = config('invoice.terms.heading', 'TERMS : E.&O.E.');
    $termsItems = config('invoice.terms.items', []);
    $bankLines = config('invoice.bank.lines', []);

    $logoAbsolutePath = public_path(config('invoice.company.logo_path', 'storage/slides/logo.jpg'));
    $logoDataUri = null;

    if (is_file($logoAbsolutePath)) {
        $ext = strtolower(pathinfo($logoAbsolutePath, PATHINFO_EXTENSION)) ?: 'png';
        $logoDataUri = 'data:image/'.$ext.';base64,'.base64_encode(file_get_contents($logoAbsolutePath));
    }

    $dt = $proforma->created_at ?? now();
    $dateDisplay = $dt->format(config('invoice.pdf.date_display_format', 'dS M-Y'));
    $datedDisplay = $dt->format(config('invoice.pdf.dated_display_format', 'd-m-Y'));

    $billingName = $proforma->targetCompany?->name ?: ($proforma->target_name ?: 'Customer');
    $billingGstin = $proforma->target_gstin ?? null;
    $billingLines = array_filter([
        $proforma->target_name ?: null,
        $proforma->target_address_line1 ?? null,
        $proforma->target_address_line2 ?? null,
        $proforma->target_city ?? null,
        $proforma->target_state ?? null,
        $proforma->target_pincode ?? null,
    ]);

    $shippingName = $proforma->shipping_name ?? $billingName;
    $shippingGstin = $proforma->shipping_gstin ?? $billingGstin;
    $shippingLines = array_filter([
        $proforma->shipping_address_line1 ?? null,
        $proforma->shipping_address_line2 ?? null,
        $proforma->shipping_city ?? null,
        $proforma->shipping_state ?? null,
        $proforma->shipping_pincode ?? null,
    ]);

    $enquiryNo = $proforma->enquiry_no ?? 'Telephonic';
    $kindAttn = $proforma->kind_attn ?? null;
    $attnContact = $proforma->attn_contact ?? null;

    $freight = (float) ($proforma->freight_amount ?? 0);
    $freightTax = (float) ($proforma->freight_tax_amount ?? 0);
    $roundOff = (float) ($proforma->round_off_amount ?? 0);

    $qtyTotal = (float) $proforma->items->sum('quantity');
    $subtotal = (float) ($proforma->subtotal ?? 0);
    $gstTotal = (float) ($proforma->tax_amount ?? 0);
    $discountTotal = (float) ($proforma->discount_amount ?? 0);
    $baseTotal = (float) ($proforma->total_amount ?? 0);
    $grandTotal = (float) ($proforma->grand_total_amount ?? ($baseTotal + $freight + $freightTax + $roundOff));

    $amountWords = null;
    try {
        if (class_exists(\NumberFormatter::class)) {
            $fmt = new \NumberFormatter('en_IN', \NumberFormatter::SPELLOUT);
            $amountWords = ucwords(trim($fmt->format($grandTotal))) . ' Rupees Only';
        }
    } catch (\Throwable $e) {
        $amountWords = null;
    }
@endphp

<table class="header-table">
    <tr>
        <td style="width:18%;" class="center">
            @if($logoDataUri)
                <img src="{{ $logoDataUri }}" alt="Logo" class="logo">
            @else
                <div class="bold">LOGO</div>
            @endif
        </td>
        <td style="width:82%;">
            <p class="title">{{ $documentTitle }}</p>
            <p class="small-line bold">{{ $sellerName }}</p>
            @foreach($sellerAddressLines as $line)
                <p class="small-line muted">{{ $line }}</p>
            @endforeach
            <p class="small-line"><span class="label">GSTIN</span>{{ $sellerGstin }}</p>
            <p class="small-line"><span class="label">State Code</span>{{ $sellerStateCode }}</p>
        </td>
    </tr>
</table>

<table class="info-table section">
    <tr>
        <td style="width:50%;">
            <p class="small-line bold">Billing To</p>
            <p class="small-line">{{ $billingName }}</p>
            @foreach($billingLines as $line)
                <p class="small-line muted">{{ $line }}</p>
            @endforeach
            <p class="small-line"><span class="label">GST</span>{{ $billingGstin ?: '-' }}</p>
            <p class="small-line"><span class="label">Kind Attn</span>{{ $kindAttn ?: '-' }}</p>
            <p class="small-line"><span class="label">Contact</span>{{ $attnContact ?: '-' }}</p>
        </td>
        <td style="width:50%;">
            <p class="small-line bold">Shipping To</p>
            <p class="small-line">{{ $shippingName }}</p>
            @foreach($shippingLines as $line)
                <p class="small-line muted">{{ $line }}</p>
            @endforeach
            <p class="small-line"><span class="label">GST</span>{{ $shippingGstin ?: '-' }}</p>
            <p class="small-line"><span class="label">PI Number</span>{{ $proforma->pi_number }}</p>
            <p class="small-line"><span class="label">Date</span>{{ $dateDisplay }}</p>
            <p class="small-line"><span class="label">Dated</span>{{ $datedDisplay }}</p>
            <p class="small-line"><span class="label">Enquiry No.</span>{{ $enquiryNo }}</p>
        </td>
    </tr>
</table>

<table class="items-table section">
    <thead>
        <tr>
            <th style="width:5%;">#</th>
            <th style="width:12%;">SKU</th>
            <th style="width:23%;">Product</th>
            <th style="width:12%;">Variant</th>
            <th style="width:10%;">Price Type</th>
            <th style="width:8%;" class="center">Qty</th>
            <th style="width:10%;" class="right">Unit Price</th>
            <th style="width:8%;" class="right">GST</th>
            <th style="width:12%;" class="right">Line Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($proforma->items as $item)
            <tr>
                <td class="center">{{ $loop->iteration }}</td>
                <td>{{ $item->sku ?: '-' }}</td>
                <td>
                    <div class="bold">{{ $item->product_name }}</div>
                    @if($item->line_subtotal)
                        <div class="muted">Base: {{ $currency }} {{ number_format((float) $item->line_subtotal, 2) }}</div>
                    @endif
                    @if($item->line_discount_amount)
                        <div class="muted">Discount: {{ $currency }} {{ number_format((float) $item->line_discount_amount, 2) }}</div>
                    @endif
                </td>
                <td>{{ $item->variant_name ?: '-' }}</td>
                <td>{{ strtoupper($item->price_type ?: '-') }}</td>
                <td class="center">{{ number_format((float) $item->quantity, 0) }}</td>
                <td class="right">{{ $currency }} {{ number_format((float) $item->unit_price, 2) }}</td>
                <td class="right">{{ $currency }} {{ number_format((float) $item->line_tax_amount, 2) }}</td>
                <td class="right">{{ $currency }} {{ number_format((float) $item->line_total, 2) }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="totals-wrap">
    <table class="totals-table">
        <tr>
            <td class="bold">Total Quantity</td>
            <td class="right">{{ number_format($qtyTotal, 0) }}</td>
        </tr>
        <tr>
            <td class="bold">Subtotal</td>
            <td class="right">{{ $currency }} {{ number_format($subtotal, 2) }}</td>
        </tr>
        <tr>
            <td class="bold">GST Total</td>
            <td class="right">{{ $currency }} {{ number_format($gstTotal, 2) }}</td>
        </tr>
        <tr>
            <td class="bold">Discount Total</td>
            <td class="right">{{ $currency }} {{ number_format($discountTotal, 2) }}</td>
        </tr>
        @if($freight != 0)
            <tr>
                <td class="bold">Freight</td>
                <td class="right">{{ $currency }} {{ number_format($freight, 2) }}</td>
            </tr>
        @endif
        @if($freightTax != 0)
            <tr>
                <td class="bold">Freight Tax</td>
                <td class="right">{{ $currency }} {{ number_format($freightTax, 2) }}</td>
            </tr>
        @endif
        @if($roundOff != 0)
            <tr>
                <td class="bold">Round Off</td>
                <td class="right">{{ $currency }} {{ number_format($roundOff, 2) }}</td>
            </tr>
        @endif
        <tr class="grand-total">
            <td>Grand Total</td>
            <td class="right">{{ $currency }} {{ number_format($grandTotal, 2) }}</td>
        </tr>
    </table>
</div>

<div class="section box">
    <p class="small-line bold">{{ $amountInWordsLabel }}</p>
    <p class="small-line">{{ $amountWords ?: '-' }}</p>
</div>

<div class="section box">
    <p class="small-line bold">{{ $termsHeading }}</p>
    @foreach($termsItems as $termIndex => $termText)
        <p class="small-line">{{ $termIndex + 1 }}. {{ $termText }}</p>
    @endforeach
</div>

<div class="section box">
    <p class="small-line bold">{{ $bankHeading }}</p>
    @foreach($bankLines as $bankLine)
        <p class="small-line">{{ $bankLine }}</p>
    @endforeach
</div>

<div class="section right muted">
    <p class="small-line">{{ $autoGeneratedText }}</p>
    <p class="small-line">{{ $signatureNote }}</p>
</div>
</body>
</html>
