<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $proforma->pi_number }}</title>
    <link rel="stylesheet" href="{{ \Illuminate\Support\Facades\Vite::asset('resources/css/app.css') }}">
</head>
<body class="m-0 bg-white font-sans text-[12px] leading-[1.45] text-slate-900">
@php
    $currency = $proforma->currency ?: config('invoice.pdf.currency', 'INR');
    $sellerName = config('invoice.company.name');
    $sellerGstin = config('invoice.company.gstin');
    $sellerStateCode = config('invoice.company.state_code');
    $sellerAddressLines = config('invoice.company.address_lines', []);
    $documentTitle = config('invoice.branding.document_title', 'PROFORMA INVOICE');
    $amountInWordsLabel = config('invoice.branding.amount_in_words_label', 'Amount in Rupees:');
    $autoGeneratedText = config('invoice.branding.auto_generated_text', 'Auto-Generated Proforma,');
    $signatureNote = config('invoice.branding.signature_note', 'Signature not required.');
    $bankHeading = config('invoice.branding.bank_heading', 'Bank Details:');
    $termsHeading = config('invoice.terms.heading', 'TERMS : E.&O.E.');
    $termsItems = config('invoice.terms.items', []);
    $bankLines = config('invoice.bank.lines', []);

    $logoAbsolutePath = public_path(config('invoice.company.logo_path', 'upload/icons/logo.jpg'));
    $logoDataUri = null;

    if (is_file($logoAbsolutePath)) {
        $ext = strtolower(pathinfo($logoAbsolutePath, PATHINFO_EXTENSION)) ?: 'png';
        $logoDataUri = 'data:image/'.$ext.';base64,'.base64_encode(file_get_contents($logoAbsolutePath));
    }

    $dt = $proforma->created_at ?? now();
    $dateDisplay = $dt->format(config('invoice.pdf.date_display_format', 'dS M-Y'));
    $datedDisplay = $dt->format(config('invoice.pdf.dated_display_format', 'd-m-Y'));

    $billingName = $proforma->targetCompany?->name ?: ($proforma->target_name ?: 'Customer');
    $billingGstin = $proforma->target_gstin ?? null;
    $billingLines = array_filter([
        $proforma->target_name ?: null,
        $proforma->target_address_line1 ?? null,
        $proforma->target_address_line2 ?? null,
        $proforma->target_city ?? null,
        $proforma->target_state ?? null,
        $proforma->target_pincode ?? null,
    ]);

    $shippingName = $proforma->shipping_name ?? $billingName;
    $shippingGstin = $proforma->shipping_gstin ?? $billingGstin;
    $shippingLines = array_filter([
        $proforma->shipping_address_line1 ?? null,
        $proforma->shipping_address_line2 ?? null,
        $proforma->shipping_city ?? null,
        $proforma->shipping_state ?? null,
        $proforma->shipping_pincode ?? null,
    ]);

    $enquiryNo = $proforma->enquiry_no ?? 'Telephonic';
    $kindAttn = $proforma->kind_attn ?? null;
    $attnContact = $proforma->attn_contact ?? null;

    $freight = (float) ($proforma->freight_amount ?? 0);
    $freightTax = (float) ($proforma->freight_tax_amount ?? 0);
    $roundOff = (float) ($proforma->round_off_amount ?? 0);

    $qtyTotal = (float) $proforma->items->sum('quantity');
    $subtotal = (float) ($proforma->subtotal ?? 0);
    $gstTotal = (float) ($proforma->tax_amount ?? 0);
    $discountTotal = (float) ($proforma->discount_amount ?? 0);
    $baseTotal = (float) ($proforma->total_amount ?? 0);
    $grandTotal = (float) ($proforma->grand_total_amount ?? ($baseTotal + $freight + $freightTax + $roundOff));

    $amountWords = null;
    try {
        if (class_exists(\NumberFormatter::class)) {
            $fmt = new \NumberFormatter('en_IN', \NumberFormatter::SPELLOUT);
            $amountWords = ucwords(trim($fmt->format($grandTotal))) . ' Rupees Only';
        }
    } catch (\Throwable $e) {
        $amountWords = null;
    }
@endphp

<div class="p-5">
    <table class="w-full border-collapse">
        <tr>
            <td class="w-[18%] border border-slate-200 p-2.5 align-top text-center">
                @if($logoDataUri)
                    <img src="{{ $logoDataUri }}" alt="Logo" class="mx-auto max-h-16 w-auto">
                @else
                    <div class="font-bold">LOGO</div>
                @endif
            </td>
            <td class="w-[82%] border border-slate-200 p-2.5 align-top">
                <p class="mb-1 text-[22px] font-bold text-slate-950">{{ $documentTitle }}</p>
                <p class="mb-1 font-bold">{{ $sellerName }}</p>
                @foreach($sellerAddressLines as $line)
                    <p class="mb-1 text-slate-600">{{ $line }}</p>
                @endforeach
                <p class="mb-1"><span class="inline-block w-24 font-bold">GSTIN</span>{{ $sellerGstin }}</p>
                <p><span class="inline-block w-24 font-bold">State Code</span>{{ $sellerStateCode }}</p>
            </td>
        </tr>
    </table>

    <table class="mt-4 w-full border-collapse">
        <tr>
            <td class="w-1/2 border border-slate-200 p-2.5 align-top">
                <p class="mb-1 font-bold">Billing To</p>
                <p class="mb-1">{{ $billingName }}</p>
                @foreach($billingLines as $line)
                    <p class="mb-1 text-slate-600">{{ $line }}</p>
                @endforeach
                <p class="mb-1"><span class="inline-block w-24 font-bold">GST</span>{{ $billingGstin ?: '-' }}</p>
                <p class="mb-1"><span class="inline-block w-24 font-bold">Kind Attn</span>{{ $kindAttn ?: '-' }}</p>
                <p><span class="inline-block w-24 font-bold">Contact</span>{{ $attnContact ?: '-' }}</p>
            </td>
            <td class="w-1/2 border border-slate-200 p-2.5 align-top">
                <p class="mb-1 font-bold">Shipping To</p>
                <p class="mb-1">{{ $shippingName }}</p>
                @foreach($shippingLines as $line)
                    <p class="mb-1 text-slate-600">{{ $line }}</p>
                @endforeach
                <p class="mb-1"><span class="inline-block w-24 font-bold">GST</span>{{ $shippingGstin ?: '-' }}</p>
                <p class="mb-1"><span class="inline-block w-24 font-bold">PI Number</span>{{ $proforma->pi_number }}</p>
                <p class="mb-1"><span class="inline-block w-24 font-bold">Date</span>{{ $dateDisplay }}</p>
                <p class="mb-1"><span class="inline-block w-24 font-bold">Dated</span>{{ $datedDisplay }}</p>
                <p><span class="inline-block w-24 font-bold">Enquiry No.</span>{{ $enquiryNo }}</p>
            </td>
        </tr>
    </table>

    <table class="mt-4 w-full border-collapse">
        <thead>
            <tr class="bg-slate-100 text-left">
                <th class="w-[5%] border border-slate-300 p-2 font-bold">#</th>
                <th class="w-[12%] border border-slate-300 p-2 font-bold">SKU</th>
                <th class="w-[23%] border border-slate-300 p-2 font-bold">Product</th>
                <th class="w-[12%] border border-slate-300 p-2 font-bold">Variant</th>
                <th class="w-[10%] border border-slate-300 p-2 font-bold">Price Type</th>
                <th class="w-[8%] border border-slate-300 p-2 text-center font-bold">Qty</th>
                <th class="w-[10%] border border-slate-300 p-2 text-right font-bold">Unit Price</th>
                <th class="w-[8%] border border-slate-300 p-2 text-right font-bold">GST</th>
                <th class="w-[12%] border border-slate-300 p-2 text-right font-bold">Line Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($proforma->items as $item)
                <tr>
                    <td class="border border-slate-300 p-2 text-center align-top">{{ $loop->iteration }}</td>
                    <td class="border border-slate-300 p-2 align-top">{{ $item->sku ?: '-' }}</td>
                    <td class="border border-slate-300 p-2 align-top">
                        <div class="font-bold">{{ $item->product_name }}</div>
                        @if($item->line_subtotal)
                            <div class="mt-1 text-slate-600">Base: {{ $currency }} {{ number_format((float) $item->line_subtotal, 2) }}</div>
                        @endif
                        @if($item->line_discount_amount)
                            <div class="mt-1 text-slate-600">Discount: {{ $currency }} {{ number_format((float) $item->line_discount_amount, 2) }}</div>
                        @endif
                    </td>
                    <td class="border border-slate-300 p-2 align-top">{{ $item->variant_name ?: '-' }}</td>
                    <td class="border border-slate-300 p-2 align-top">{{ strtoupper($item->price_type ?: '-') }}</td>
                    <td class="border border-slate-300 p-2 text-center align-top">{{ number_format((float) $item->quantity, 0) }}</td>
                    <td class="border border-slate-300 p-2 text-right align-top">{{ $currency }} {{ number_format((float) $item->unit_price, 2) }}</td>
                    <td class="border border-slate-300 p-2 text-right align-top">{{ $currency }} {{ number_format((float) $item->line_tax_amount, 2) }}</td>
                    <td class="border border-slate-300 p-2 text-right align-top">{{ $currency }} {{ number_format((float) $item->line_total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="mt-4 ml-auto w-[42%]">
        <table class="w-full border-collapse">
            <tr>
                <td class="border border-slate-200 p-2 font-bold">Total Quantity</td>
                <td class="border border-slate-200 p-2 text-right">{{ number_format($qtyTotal, 0) }}</td>
            </tr>
            <tr>
                <td class="border border-slate-200 p-2 font-bold">Subtotal</td>
                <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($subtotal, 2) }}</td>
            </tr>
            <tr>
                <td class="border border-slate-200 p-2 font-bold">GST Total</td>
                <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($gstTotal, 2) }}</td>
            </tr>
            <tr>
                <td class="border border-slate-200 p-2 font-bold">Discount Total</td>
                <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($discountTotal, 2) }}</td>
            </tr>
            @if($freight != 0)
                <tr>
                    <td class="border border-slate-200 p-2 font-bold">Freight</td>
                    <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($freight, 2) }}</td>
                </tr>
            @endif
            @if($freightTax != 0)
                <tr>
                    <td class="border border-slate-200 p-2 font-bold">Freight Tax</td>
                    <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($freightTax, 2) }}</td>
                </tr>
            @endif
            @if($roundOff != 0)
                <tr>
                    <td class="border border-slate-200 p-2 font-bold">Round Off</td>
                    <td class="border border-slate-200 p-2 text-right">{{ $currency }} {{ number_format($roundOff, 2) }}</td>
                </tr>
            @endif
            <tr class="bg-slate-900 text-white">
                <td class="border border-slate-900 p-2 font-bold">Grand Total</td>
                <td class="border border-slate-900 p-2 text-right font-bold">{{ $currency }} {{ number_format($grandTotal, 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="mt-4 rounded-lg border border-slate-300 p-3">
        <p class="mb-1 font-bold">{{ $amountInWordsLabel }}</p>
        <p>{{ $amountWords ?: '-' }}</p>
    </div>

    <div class="mt-4 rounded-lg border border-slate-300 p-3">
        <p class="mb-1 font-bold">{{ $termsHeading }}</p>
        @foreach($termsItems as $termIndex => $termText)
            <p class="mb-1">{{ $termIndex + 1 }}. {{ $termText }}</p>
        @endforeach
    </div>

    <div class="mt-4 rounded-lg border border-slate-300 p-3">
        <p class="mb-1 font-bold">{{ $bankHeading }}</p>
        @foreach($bankLines as $bankLine)
            <p class="mb-1">{{ $bankLine }}</p>
        @endforeach
    </div>

    <div class="mt-4 text-right text-slate-600">
        <p class="mb-1">{{ $autoGeneratedText }}</p>
        <p>{{ $signatureNote }}</p>
    </div>
</div>
</body>
</html>
