<?php

return [
    'members' => [
        [
            'name' => 'Mr. Santosh Srivastava',
            'role' => 'Founder & Managing Director',
            'img' => 'https://ui-avatars.com/api/?name=Santosh+Srivastava&background=d1f0dd&color=1A4D2E&size=500&bold=true',
            'copy' => "Mr. Santosh Srivastava is the visionary founder and driving force behind Biogenix, with over two decades of deep-rooted experience in the diagnostics and medical devices industry. A postgraduate in Commerce (M.Com.) from Lucknow University, he entered the healthcare sector in the late 1990s, where he spent several years gaining extensive industry exposure and developing a strong foundation in diagnostics and product distribution.\n\nIn 2007, he established Biogenix with a clear vision to build a reliable and growth-oriented healthcare solutions company. Starting as a distribution firm, the company initially focused on ELISA kits, rapid tests, and biochemistry products, where Mr. Srivastava quickly established a strong market presence. His expertise in ELISA products earned him a reputation as a specialist in the segment, making it one of the core strengths of the organization.\n\nWith a forward-looking mindset and a strong belief in vertical integration, he laid the foundation for Biogenix’s manufacturing capabilities in 2017, marking a significant transition from distribution to production. Under his leadership, the company has steadily expanded its product portfolio to cater to the evolving needs of hospitals, diagnostic centres, and healthcare institutions across India.\n\nMr. Srivastava is deeply involved in every aspect of the business, maintaining a hands-on leadership style that emphasizes personal engagement over passive oversight. From shaping marketing strategies to directing financial planning and overseeing operational decisions, his involvement spans across all departments. His approach is rooted in precision, experience, and a strong belief in direct interaction and real-world understanding of the business.\n\nOver the years, he has successfully positioned Biogenix both domestically and in international markets, building credibility and recognition for the brand. His leadership continues to be the cornerstone of the company’s growth, resilience, and long-term vision, making him an integral force behind Biogenix’s sustained success.\n\nIn recognition of his contributions to the healthcare and diagnostics industry, Mr. Srivastava has been frequently featured in leading business and industry publications, including Forbes and Fortune. His work and leadership have also been highlighted across prominent media platforms such as Times Now, ABP News, and various healthcare and MedTech publications, including Medgate.\n\nHe has received multiple awards and recognitions for his contribution to the medical device industry, including honours from the Government of Uttar Pradesh."
        ],
        [
            'name' => 'Mrs. Dimple Srivastava',
            'role' => 'Director – Operations & Administration',
            'img' => 'https://ui-avatars.com/api/?name=Dimple+Srivastava&background=d1f0dd&color=1A4D2E&size=500&bold=true',
            'copy' => "Mrs. Dimple Srivastava brings a unique blend of academic grounding, discipline, and hands-on operational leadership to Biogenix. Holding a Master’s degree in Commerce (M.Com.) from Lucknow University, she began her professional journey in education, dedicating over a decade to teaching and shaping young minds. This early experience instilled in her a strong sense of structure, responsibility, and people management—qualities that continue to define her leadership style today.\n\nTransitioning from academia to business in the 2010s, she gradually became deeply involved in the company’s internal ecosystem and later joined Biogenix full-time. Since then, she has been a central force behind the organization’s operational stability, overseeing a wide range of functions that keep the company running seamlessly on a day-to-day basis.\n\nHer responsibilities span across administration, human resources, production coordination, and logistics management. She plays a key role in workforce management, including payroll structuring and salary administration, while also ensuring discipline and efficiency across departments. From supervising internal workflows to supporting production and SCM operations, her involvement is both comprehensive and detail-oriented.\n\nMrs. Srivastava’s leadership is defined by consistency, accountability, and a deep sense of ownership. Her ability to manage multiple critical functions simultaneously has made her an indispensable pillar of Biogenix’s operational framework, ensuring that the organization functions with precision, reliability, and continuity."
        ],
        [
            'name' => 'Mr. Arvind Singh Negi',
            'role' => 'Technical Director',
            'img' => 'upload/team/Arvind Negi - pfp.jpeg',
            'copy' => "Mr. Arvind Singh Negi serves as the Technical Director at Biogenix, bringing with him over a decade of dedicated experience within the organization. Over the years, he has established himself as a critical pillar in managing the company’s technical operations, regulatory compliance, and government business functions.\n\nHe leads the entire technical ecosystem of Biogenix, overseeing the performance and coordination of service engineers and technical staff. His role involves ensuring seamless execution of both internal operations and external service support, including timely resolution of client service requests and maintaining high standards of technical reliability across all product lines.\n\nA key area of his expertise lies in handling government business through the GeM (Government e-Marketplace) platform. Mr. Negi manages end-to-end operations related to government procurement, making him instrumental in securing and executing institutional business for the company. His deep understanding of the platform and associated processes has significantly strengthened Biogenix’s presence in the government sector.\n\nIn addition to technical and government operations, he is responsible for overseeing regulatory and compliance-related functions. This includes managing product approvals, licensing, and registrations across manufacturing and imported product categories. From ensuring adherence to industry standards to facilitating import-export documentation and quality assurance protocols, his role is central to maintaining the company’s regulatory integrity.\n\nMr. Negi’s leadership is defined by precision, technical depth, and a strong command over complex operational frameworks. His ability to integrate technical execution with compliance and government processes makes him an indispensable contributor to Biogenix’s sustained growth and operational excellence."
        ],
        [
            'name' => 'Mr. Shyam Narayan Srivastava',
            'role' => 'Director – Finance & Accounting',
            'img' => 'upload/team/Shyam N. Srivastava - pfp.jpeg',
            'copy' => "Mr. Shyam Narayan Srivastava serves as the Director of Finance & Accounting at Biogenix, bringing over a decade of dedicated experience in managing the company’s financial and operational backbone. His role is central to ensuring financial discipline, transparency, and strategic resource allocation across the organization.\n\nHe oversees and executes the full spectrum of financial functions, including the preparation, analysis, and monitoring of financial statements. His structured approach to financial management enables informed decision-making and supports the company’s long-term growth objectives. With a strong command over numbers and financial systems, he ensures accuracy, compliance, and fiscal stability at every level.\n\nBeyond core finance, Mr. Srivastava plays a key role in procurement strategy and execution. He manages procurement activities with a focus on cost efficiency, vendor coordination, and supply optimization, contributing significantly to operational effectiveness. His ability to align procurement decisions with financial planning adds strategic value to the company’s supply chain.\n\nHe is also deeply involved in managing import and export operations, particularly handling documentation, regulatory compliance, and coordination with clearing agents and logistics partners. His attention to detail and process-driven approach ensure smooth execution of cross-border transactions and timely fulfilment of operational requirements.\n\nMr. Srivastava’s leadership is defined by precision, reliability, and a strong sense of accountability. His comprehensive control over financial, procurement, and documentation processes makes him a vital pillar in maintaining the company’s operational integrity and financial strength."
        ],
        [
            'name' => 'Mr. Ashwini Kumar Mishra',
            'role' => 'Director – Research & Development',
            'img' => 'upload/team/Ashwani Kumar - pfp.jpeg',
            'copy' => "Mr. Ashwini Kumar Mishra serves as the Director of Research & Development at Biogenix, bringing over 17 years of extensive experience across life sciences, biotechnology, genomics, proteomics, and molecular diagnostics. With a strong foundation in both research and industry, he leads the company’s innovation strategy and is the driving force behind the development of advanced diagnostic solutions.\n\nSince joining Biogenix in the early 2020s, Mr. Mishra has been instrumental in establishing and scaling the company’s microbiology and molecular diagnostics division. He independently oversees all activities within the department, from research and product development to validation and implementation, ensuring that Biogenix remains aligned with evolving global healthcare standards.\n\nHis core expertise lies in advanced genomic and proteomic technologies, including PCR, sequencing, SNP genotyping, bioinformatics analysis, and LC-MS/MS.\n\nAt Biogenix, his current focus is on developing innovative and accessible diagnostic technologies across areas such as infectious diseases, genetic testing, newborn screening, prenatal and postnatal diagnostics, and automated systems including blood culture and continuous monitoring solutions. Under his leadership, the R&D division is committed to delivering high-quality, ISO 13485-compliant products that aim to make diagnostics simpler, more accurate, and more affordable.\n\nMr. Mishra’s leadership combines deep scientific expertise with a forward-looking vision, making him a key driver of Biogenix’s transition into a research-driven, innovation-led healthcare organization."
        ],
        [
            'name' => 'Mr. Shailendra Kumar Ghosh',
            'role' => 'Director – Sales & Marketing',
            'img' => 'upload/team/Shailendra Ghosh - pfp.jpeg',
            'copy' => "Mr. Shailendra Kumar Ghosh serves as the Director of Sales & Marketing at Biogenix and is one of the longest-standing pillars of the organization. With over 15 years of dedicated service to the company, he plays a critical role in shaping Biogenix’s market presence and revenue growth.\n\nBringing more than two decades of experience in the diagnostics and healthcare industry, Mr. Ghosh has developed deep expertise in sales strategy, market expansion, and client relationship management. He began his professional journey in the early 2000s and has since built a strong understanding of the evolving dynamics of the Indian healthcare market.\n\nAt Biogenix, he leads all sales and marketing operations across Northern half of India, managing a vast network of clients, distributors, and institutional relationships. He is responsible for driving the company’s entire private sector business, overseeing product sales, market penetration strategies, and revenue generation across multiple segments.\n\nMr. Ghosh has been instrumental in building and nurturing Biogenix’s private sector clientele from the ground up. A significant portion of the company’s customer base, including diagnostic centres, hospitals, and private institutions, has been developed and sustained through his consistent efforts and relationship-driven approach.\n\nHis leadership is characterized by strong market intuition, execution excellence, and long-term relationship building. With a hands-on approach to sales and a deep commitment to business growth, he continues to be a key force behind Biogenix’s expanding footprint and sustained success in the private healthcare sector."
        ],
        [
            'name' => 'Mr. Sanjay Kumar Yadav',
            'role' => 'Plant Head & Head of Production – Biochemistry Division',
            'img' => 'upload/team/Sanjay yadav - pfp.JPG',
            'copy' => "Mr. Sanjay Kumar Yadav serves as the Plant Head and Head of Production for the Biochemistry Division at Biogenix, bringing with him strong technical expertise and hands-on experience in manufacturing and quality control. A postgraduate in Biochemistry from CSJMU, Kanpur, he combines academic knowledge with practical industry exposure to ensure high standards across production processes.\n\nWith over five years at Biogenix, Mr. Yadav has established himself as a key figure in the company’s manufacturing operations. He is responsible for overseeing the entire production ecosystem, ensuring that all manufacturing activities are executed efficiently, consistently, and in compliance with quality standards.\n\nHe directly supervises production lines across multiple product categories, maintaining strict control over processes, output quality, and workflow efficiency. His expertise in quality management, particularly within the biochemistry segment, plays a crucial role in maintaining the reliability and performance of Biogenix products.\n\nMr. Yadav has been instrumental in the in-house manufacturing of more than 50 biochemistry reagents at Biogenix, contributing significantly to the company’s production capabilities and product portfolio expansion. His attention to detail and process-oriented approach ensure that every product meets defined specifications and industry benchmarks.\n\nHis leadership style is grounded in discipline, consistency, and technical precision. By closely monitoring both production and quality functions, he ensures seamless coordination between departments and maintains operational excellence within the manufacturing unit. Mr. Yadav continues to play a vital role in strengthening Biogenix’s position as a reliable and quality-driven manufacturer in the diagnostics industry."
        ],
        [
            'name' => 'Mr. Brijesh Pandey',
            'role' => 'Head of Production – Rapid Diagnostics (Lateral Flow Division)',
            'img' => 'upload/team/Brijesh Pandey - pfp.JPG',
            'copy' => "Mr. Brijesh Pandey serves as the Head of Production for the Rapid Diagnostics (Lateral Flow) Division at Biogenix, bringing over 12 years of specialized experience in the development and manufacturing of rapid diagnostic kits. With a strong academic foundation in Biotechnology, he combines scientific expertise with extensive hands-on experience in production and process management.\n\nSince joining Biogenix in 2020, Mr. Pandey has played a pivotal role in establishing and scaling the company’s lateral flow test manufacturing capabilities. He currently oversees the in-house production of more than 40 rapid diagnostic products, including lateral flow assays, dipsticks, and flow-through tests, contributing significantly to the company’s rapid diagnostics portfolio.\n\nHis expertise spans across research and development, production planning, and operational execution, with a strong focus on maintaining efficiency and consistency across manufacturing processes. He ensures that all production activities are aligned with Good Manufacturing Practice (GMP) standards, maintaining strict control over quality, compliance, and workflow management.\n\nMr. Pandey is also a government-approved Manufacturing Chemist, recognized by the Drugs Control Department, Government of Himachal Pradesh, for the production of rapid diagnostic and immunodiagnostic kits. This accreditation underscores his technical credibility and regulatory competence in the field.\n\nThroughout his career, he has contributed to the development and manufacturing of a wide range of IVD rapid tests, including recently introduced products such as the Sickle Cell Rapid Test. His ability to translate scientific knowledge into scalable production systems has been instrumental in strengthening Biogenix’s manufacturing capabilities in the rapid diagnostics segment.\n\nMr. Pandey’s leadership is defined by technical precision, regulatory awareness, and a results-driven approach. His role is critical in ensuring that Biogenix continues to deliver reliable, high-quality rapid diagnostic solutions to the market."
        ],
        [
            'name' => 'Mr. Jalaj Pant',
            'role' => 'Assistant Manager – Operations, Regulatory & Government Affairs',
            'img' => 'upload/team/Jalaj Pant - pfp.jpeg',
            'copy' => "Mr. Jalaj Pant plays a dynamic and evolving role within Biogenix, contributing across multiple critical functions including operations, regulatory affairs, and government business execution. With over five years of experience in the organization, he has steadily grown into a key support system within the company’s operational and compliance framework.\n\nWorking closely under the guidance of the Technical Director, Mr. Arvind Singh Negi, he is deeply involved in executing and managing a wide range of responsibilities that span technical coordination, regulatory processes, and government procurement activities. His role is integral to ensuring that backend operations are carried out efficiently and in alignment with organizational goals.\n\nHe maintains close coordination with regulatory authorities, ensuring timely approvals and adherence to evolving guidelines and industry requirements.\n\nIn addition to regulatory functions, he has played a significant role in handling government tenders and procurement processes through platforms such as GeM and other e-tendering systems. His understanding of documentation, submission protocols, and follow-up processes contributes directly to the company’s success in institutional business.\n\nOver the course of his journey at Biogenix, Mr. Pant has worked across multiple departments, gaining exposure to quality assurance systems, administrative operations, and digital coordination tasks. From supporting ISO compliance and internal audits to managing backend workflows, client coordination, and internal documentation systems, his versatility makes him a valuable operational asset.\n\nHis growth within the organization reflects adaptability, consistency, and a strong willingness to take ownership of responsibilities. With a solid foundation across regulatory, administrative, and operational domains, Mr. Pant continues to strengthen the internal execution capabilities of Biogenix."
        ],
        [
            'name' => 'Mr. Jyoti Ranjan Pradhan',
            'role' => 'Export Manager – International Business',
            'img' => 'https://ui-avatars.com/api/?name=Jyoti+Ranjan+Pradhan&background=d1f0dd&color=1A4D2E&size=500&bold=true',
            'copy' => "Mr. Jyoti Ranjan Pradhan serves as the Export Manager at Biogenix, leading the company’s international business operations with a strong focus on global market expansion and cross-border trade execution. With over seven years of experience in international sales and marketing, he brings valuable expertise in managing global distribution networks and building sustainable international partnerships.\n\nSince joining Biogenix in 2020, Mr. Pradhan has played a key role in strengthening the company’s presence across international markets. He is responsible for developing and executing export strategies aligned with the organization’s growth objectives, with a focus on entering new markets, expanding distribution channels, and maximizing global revenue opportunities.\n\nHe has successfully managed export operations across more than 2 country spanning Europe, Asia, the Middle East, and Africa. His role involves overseeing the complete export lifecycle, including documentation, compliance with international trade regulations, and coordination with logistics and shipping partners to ensure timely and efficient delivery.\n\nMr. Pradhan brings strong expertise in handling complex export documentation processes, including invoices, shipping documentation, certificates of origin, and customs compliance. His attention to regulatory requirements ensures that all international transactions are executed smoothly and in accordance with global standards.\n\nIn addition to operational responsibilities, he plays a crucial role in building and maintaining long-term relationships with international distributors, clients, and business partners. His ability to negotiate effectively and understand cross-cultural business dynamics has contributed significantly to Biogenix’s growing global footprint.\n\nHe is also actively involved in supporting OEM and customized product development tailored to the specific needs of different regional markets, enabling the company to remain competitive and relevant across diverse geographies.\n\nMr. Pradhan’s approach combines analytical thinking, strategic planning, and relationship-driven execution. His leadership in international business continues to drive Biogenix’s expansion into global markets, reinforcing its position as an emerging player in the international diagnostics industry."
        ],
    ]
];
